#!/bin/bash
set -e

# This is a simple script to create user services with full privileges.
# Be careful!. 

# DOCKER_IMAGE="postgres"
DOCKER_IMAGE="custom-postgres"

docker-compose exec -u postgres $DOCKER_IMAGE psql
